### ISSUE TITLE
3DS2 request fail

### ISSUE THREAD

**Issue by azhar-gtl** [Worldpay/Worldpay-Magento2-CG#100]
Magento ver. 2.4.1 
Browser: Chrome Version 106.0.5249.91
sapient/module-worldpay: 2.4.1-rc1220

When I complete the 3DS2 check correctly the Worldpay plugin redirects me back to the website but we could not complete the order.

While checking the logs request XML data was sent properly and got the response for that, Also notice that the extension retrieve the payment many time for completing the request but it gives the following error in response.

**After 3DS2 Reqeust**
<!DOCTYPE paymentService PUBLIC "-//WorldPay//DTD WorldPay PaymentService v1//EN"
                                "http://dtd.worldpay.com/paymentService_v1.dtd">
<paymentService version="1.4" merchantCode="mymerchantcode"><reply><orderStatus orderCode="000001234564-89746545"><error code="7"><![CDATA[Could not find order]]></error></orderStatus></reply></paymentService>

**Retrive pament request**
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE paymentService PUBLIC "-//WorldPay//DTD WorldPay PaymentService v1//EN"
                                "http://dtd.worldpay.com/paymentService_v1.dtd">
<paymentService version="1.4" merchantCode="mymerchantcode"><reply><orderStatus orderCode="000001234564-89746545"><error code="5"><![CDATA[Could not find payment for order]]></error></orderStatus></reply></paymentService>
 
According to the flow, it should redirect post-checkout page where it redirects to thank you page. It should also display the order number in the backend with the status set as SENT_FOR_AUTHORISATION.

This extension worked properly earlier, but the issue occurred last two months since we didn't update the code or configuration. We have logs for successful orders as well.

Please if you can help us to resolve this issue as soon as possible, we have connected with the WorldPay team and provided all logs and files. Reference # 221103-000144

Regards,
Azharuddin Shaikh

**Comment by elavarasann** [comment]
Hi,
Seem like you are using very older version, please use our latest release which you can find in below GitHub link,
https://github.com/Worldpay/Worldpay-Magento2-CG/releases/tag/2.4.5-p10123
