### ISSUE TITLE
Getting order confirmation email before payment complete

### ISSUE THREAD

**Issue by deemantha22** [Worldpay/Worldpay-Magento2-CG#104]
Hi,

Need advice please.

We are getting one order email when click 'Continue to Worldpay' button,  another one once customer pay.

**Comment by elavarasann** [comment]
Hi,
The first email is for the order confirmation and second email is for the confirmation of Payment authorization.

**Comment by deemantha22** [comment]
Hi @elavarasann 

Thanks for getting back. 

Can we disable order confirmation and leave only confirmation of Payment authorization?

**Comment by elavarasann** [comment]
No, currently it is not possible. But you can customize as per your requirement.
