### ISSUE TITLE
Apple Pay, Google Pay

### ISSUE THREAD

**Issue by obsergiu** [Worldpay/Worldpay-Magento2-CG#109]
Any chance for apple pay/google pay on the product page to get appropriately implemented? 

Right now it displays a form where the customer needs to input his address and other personal information. 
This is not how it should be working. 

Any standard implementation would pull this type of data from ApplePay/GooglePay, that's their major benefit. 

This is not very difficult to be done so I'm not sure why it was not done, are there any dependencies we're not aware of?

**Comment by elavarasann** [comment]
We will check in our side and update you.
