### ISSUE TITLE
Purpose of transaction

### ISSUE THREAD

**Issue by deemantha22** [Worldpay/Worldpay-Magento2-CG#112]
Hi,

APM payments, is there a way to enable/disable 'Purpose of transaction' textarea from admin?
Printscreen attached
<img width="746" alt="Screenshot 2023-04-06 at 13 34 15" src="https://user-images.githubusercontent.com/104432639/230379989-7a945e69-15b3-4b85-b379-6a20e41f81d1.png">

**Comment by elavarasann** [comment]
Hi,
Currently we dont have that option.
