### ISSUE TITLE
APMs(Sofort,Bancontact/MisterCash,AliPay) -  “There are no payment methods available at this time. Please contact the merchant.”

### ISSUE THREAD

**Issue by obsergiu** [Worldpay/Worldpay-Magento2-CG#121]
Hello, 

We are currently facing critical issues with the Alternative Payment Methods (APMs) in the Worldpay module of our system. After discussions with our Worldpay account manager, we have identified a common error message affecting multiple payment methods:

__Error Message:__
*"There are no payment methods available at this time. Please contact the merchant."*

The affected payment methods include:

**Sofort Payment Method:**
- **Suggested Solution:** We recommend adding parameters for "country=DE" and "preferredPaymentMethod=SOFORT-SSL" by default to ensure proper functionality.

**Bancontact/MisterCash Payment Method:**
- **Geographic Restriction:** This payment method is only available in Belgium.
- **Suggested Solution:** Urgent modifications are needed to append the Redirect URL with "&countryCode=BE" when Bancontact/MisterCash is selected for Belgium. Additionally, the module should allow us to send the country code "DE" when it is chosen for Germany in the XML request.

**AliPay:**
- **Suggested Solution:** We emphasize the necessity of including the parameter "&country=CN&preferredPaymentMethod=ALIPAY-SSL" in the XML request to specify the country code and ensure AliPay's functionality.

We kindly request your prompt attention to these issues as they are affecting our payment processing capabilities. 

Thank you

**Comment by elavarasann** [comment]
Hi,

Thanks for the update, could you please give us more details about the env that your using by answering below questions ?

1) Magento version ?
2) Worldpay Plugin version ?
3) Any third-party plugins they have installed ?
4) Have you checked if the issue persists on a vanilla (unmodified) version?

**Comment by obsergiu** [comment]
Hi, 

1. Magento version:  2.4.6-p2
2. plugin version:      2.4.6-p21023
3. no other plugins related to payments 
4. yes, it was tested in the vanila version and it's the same behaviour. 

thank you for looking into this

**Comment by elavarasann** [comment]
Hi,

We have tried in our with Same Magento Vanilla version and Worldpay plugin version. We have not facing any issue. Screenshot for your reference.
![image-2023-12-12-12-14-12-628](https://github.com/Worldpay/Worldpay-Magento2-CG/assets/5245575/2e1eec25-3745-43d9-98db-7f1c19bec651)
  
![image-2023-12-12-12-18-18-416](https://github.com/Worldpay/Worldpay-Magento2-CG/assets/5245575/28e3bf79-e837-45e8-9a67-c4a702927695)

**Comment by obsergiu** [comment]
This was not enabled on the Worldpay side, which they assured us it was and provided the upper changes. 
Closing the ticket.

**Comment by obsergiu** [comment]
the ticket can be closed
