### ISSUE TITLE
PHP Fatal error:  Class Sapient\Worldpay\Model\PaymentMethods\CcVault may not inherit from final class (Magento\Vault\Model\Method\Vault)

### ISSUE THREAD

**Issue by BrianBi** [Worldpay/Worldpay-Magento2-CG#14]
PHP Fatal error:  Class Sapient\Worldpay\Model\PaymentMethods\CcVault may not inherit from final class (Magento\Vault\Model\Method\Vault) in /vendor/sapient/module-worldpay/Model/PaymentMethods/CcVault.php on line 270

**Comment by nathanjhastings** [comment]
Same issue here, class is attempting to extend a final defined class - http://php.net/manual/en/language.oop5.final.php

> PHP 5 introduces the final keyword, which prevents child classes from overriding a method by prefixing the definition with final. **If the class itself is being defined final then it cannot be extended**.

Using PHP 7.0.33, Magento 2.1.10

Is there a patch or workaround available for this?

**Comment by elavarasann** [comment]
Could you please give us more data ? Because we are not able to reproduce this issue in our side. It would be great if you send us the steps to reproduce it.

**Comment by nathanjhastings** [comment]
Sure, I followed the traditional installation from page 4 of the guide:

> Traditional Installation
> For installation of extension using traditional non-composer way, Please follow below steps:
> 1. Download the extension zip file from https://github.com/Worldpay/Worldpay-Magento-CG
> 2. Unzip the file in a temporary directory
> 3. Please cross check if there is any code folder under app folder path Magento2Rootfolder/app
> a. If exist please upload it to your code directory.
> b. If there is no code folder please copy the extracted folder to
> app/code/Sapient/Worldpay folder.
> 4. Disable the cache under System >> Cache Management
> 5. Enter the following at the command line: php f bin/magento2 setup: upgrade

I then received this fatal error:

> PHP Fatal error:  Class Sapient\Worldpay\Model\PaymentMethods\CcVault may not inherit from final class (Magento\Vault\Model\Method\Vault) in /chroot/home/a7446e05/staging.millersmusic.co.uk/html/app/code/Sapient/Worldpay/Model/PaymentMethods/CcVault.php on line 270

Please let me know if there is any further information I can provide or code change I can test.

**Comment by elavarasann** [comment]
Thanks for your inputs. I have checked the code. In Magento 2.1.10 the class Magento\Vault\Model\Method\Vault.php described as final class. i.e 

```
**final** class Vault implements VaultPaymentInterface {
....
}
```

But on later versions (I don't know exactly which version) they have removed the final class. In 2.2.5 and 2.3 I have checked.
i.e.
```
class Vault implements VaultPaymentInterface {
...
}
```
So that's the reason we are not getting this error but you. If you can update the Magento version to latest or at least 2.2.5 will solve this issue. And we are also looking for best solution for this issue.

**Comment by BrianBi** [comment]
@elavarasann I'll try to update it，Thanks!

**Comment by kiber** [comment]
I had the same issue with Magento 2.1.12 and seems the last version of the module will not work with Magento 2.1.x versions.
But you have mentioned that it will work starting from 2.1.8
https://worldpay.github.io/Worldpay-Magento2-CG/
Please also update **composer.json** with proper requirements.

and **final class** concept removed starting from Magento 2.2.0
