### ISSUE TITLE
Unexpected Behaviour in Worldpay Payment module

### ISSUE THREAD

**Issue by Ahtisham-Ali149** [Worldpay/Worldpay-Magento2-CG#144]
Hi,
We've been using Worldpay Payment Module for almost 2 years, but today all of a sudden we've noticed a strange behaviour. We are getting multiple forms, on checkout even though they're disabled from from Configurations.

![image](https://github.com/user-attachments/assets/44380501-4d62-4b85-9c58-5b5f9b39cf6e)
![image](https://github.com/user-attachments/assets/8e81f3a2-8c7f-4cde-8034-34c033ff744f)

Please respond it asap cuz it is our live site and users are already complaining a lot.

**Comment by twinklekumarsapient** [comment]
Hi,

Could you please let us know the following information? It will help us debug the issue:

1. Magento version
2. Worldpay plugin version
3. PHP version
4. Did you check this issue on the vanilla version of Magento without any customization or third-party modules?

Thank you.
