### ISSUE TITLE
Failed to load the "Sapient_Worldpay/js/view/payment/method-renderer/cc-method" component. console-output-handler.js:34 [2018-09-12 04:11:05] [ERROR] 

### ISSUE THREAD

**Issue by sajidpatel** [Worldpay/Worldpay-Magento2-CG#15]
Getting the following error on checkout, if order contains virtual products / no shipping address:

console-output-handler.js:34 [2018-09-12 04:11:05] [ERROR] Failed to load the "Sapient_Worldpay/js/view/payment/method-renderer/cc-method" component.

**Comment by elavarasann** [comment]
Issue has been fixed, hence closing the ticket

**Comment by daniloab** [comment]
This issue was fixed how? I'm facing this same error but for my extension.
