### ISSUE TITLE
Magento 2 multistore with order prefix causes Worldpay payments to fail

### ISSUE THREAD

**Issue by sajidpatel** [Worldpay/Worldpay-Magento2-CG#17]
If we set a prefix to sales_order.increment_id using sequence_profile then worldpay_payment.order_id shows as 4294967295.  Which causes the world pay payment to fail.

**Comment by elavarasann** [comment]
This plugin is developed by using vennila version of Magento. So you have to configure the plugin as per the additional changes you have.
