### ISSUE TITLE
Source class "\Worldpay\Payments" for "\Worldpay\Payments\Logger" generation does not exist.

### ISSUE THREAD

**Issue by Nicfi** [Worldpay/Worldpay-Magento2-CG#18]
Hi - trying to install on Magento-CE-2.2.6-2018-09-07-02-17-04, but get the above message whilst running php -f bin/magento setup:upgrade.

Site or Admin will then not work, resolved by removing         'Worldpay_Payments' => 1 from app/etc/config.php

can you help please... 
Thanks.

**Comment by elavarasann** [comment]
Our plugin will not have entry such as "Worldpay_Payments" in config.php file. It seams you are using different module. Our module will have entry in config.php as "'Sapient_Worldpay' => 1". Hence closing the ticket. Please check again.
