### ISSUE TITLE
sapient/module-worldpay is not compatible with PHP 7.2

### ISSUE THREAD

**Issue by schiriac** [Worldpay/Worldpay-Magento2-CG#19]
When installing the module via composer, I receive the error that the module is not compatible with PHP 7.2:
`sapient/module-worldpay 1.5.3 requires php ~5.5.0|~5.6.0|~7.0.0|~7.1.0 -> your PHP version (7.2.4) does not satisfy that requirement.
`

**Comment by chandan-PS** [comment]
We are working on Magento 2.3 (using PHP 7.2.x) compatibility and it will be released soon.

**Comment by elavarasann** [comment]
Our latest release (2.1.7) supports PHP7.2 with Magento 2.3.4
