### ISSUE TITLE
Credit Card option is not display at checkout

### ISSUE THREAD

**Issue by masterdef** [Worldpay/Worldpay-Magento2-CG#2]
Hello,

We setup module to our test store, conifgure Merchant Code, XML username and password
but Credit Card option do not display at checkout
https://drive.google.com/file/d/1KFXb6bDMWanzmV1YSjUk_gFdxhuUW5NL/view?usp=drivesdk

And not errors in log files.
Any notes how to debug checkout process?

Thanks

**Comment by lochansim** [comment]
Hello Masterdef,

Could you send a screen grab of the Worldpay configuration in Magento to
plugins[at]worldpay.com and I'll take a look!

**Comment by masterdef** [comment]
Hello Lochan,

Just sent email to plugins@
Re: [Worldpay/Worldpay-Magento2-CG] Credit Card option is not display at checkout (#2)

Thanks!

**Comment by masterdef** [comment]
Hello Lochan,

Any feedback on my email and/or API requests?
just want to move forward with module debug to implement into our store.

Thanks,
Andrew
