### ISSUE TITLE
Broken checkout in Internet Explorer when using APM's

### ISSUE THREAD

**Issue by tprocter-ldg** [Worldpay/Worldpay-Magento2-CG#20]
When trying to checkout in Internet Explorer and reaching step two of the onepage checkout (billing/payment information section), the checkout crashes because of an error on line 56 of the /apm-method.js file. 

**Error:** 
SCRIPT 1006: Expected ')'
File: apm-method.js, Line 56, Column: 46

It seems to be the filterAjax function is trying to add a default value of 'null' to statusCheck parameter but this functionality was brought in to ECMAScript 6/2015 which is NOT supported in any version of Internet Explorer. 

**FIX:**
Removing the '= null' prevents the checkout from crashing and this shouldn't cause further issues as this function is only called twice, both times from this file and both times a value of 1 is passed through. 

Quick fix is to copy this file into your theme directory and remove the '= null'.

**Comment by elavarasann** [comment]
We have fixed this issue, and the fix is available in the current latest version of this plugin. i.e. 2.1.3

The same issue was happened in normal credit card order (cc-method.js) and Google Pay order (wallets-method.js) also fixed in this release.
