### ISSUE TITLE
Stored Credentials

### ISSUE THREAD

**Issue by Jason-S-M** [Worldpay/Worldpay-Magento2-CG#21]
Wordplay have released the details of the new required Stored Credentials integration for Visa and Mastercard token payments, and Mechant Initiated Transactions for both card and Pay As Order,

are you going to release an update to incorporate the new requirements, the deadline from Worldpay is 30th Apr 2019 !!

**Comment by chandan-PS** [comment]
Hi @Jason-S-M , if you are asking about Stored Credentials feature - then yes we have already implemented it and you can find that in our latest release as well.

**Comment by chandan-PS** [comment]
I am closing this ticket for now, open a new one if you need any support.
