### ISSUE TITLE
Worldpay

### ISSUE THREAD

**Issue by imran-solangin** [Worldpay/Worldpay-Magento2-CG#22]
Hi,
How much time will you update this plugin for php 7.1 , 7.2 , 7.3 & also in  magento 2.2.7 , 2.3.0 version.

**Comment by elavarasann** [comment]
Hi, 
  Your question is not clear, please update it.

**Comment by imran-solangin** [comment]
support magento 2.2.7 & 2.3.0 or if not supported how much it will update to support these versions.

**Comment by elavarasann** [comment]
Our current release (2.0.0) is comfortable with Magento 2.2.5 and 2.3.0. I think it will work on 2.2.7 also, but  never tested with that.

**Comment by imran-solangin** [comment]
I have configure it in magento 2.2.7 but I am facing this error, I have attached screenshot

![error](https://user-images.githubusercontent.com/31388611/59265008-e26aad80-8c5d-11e9-977e-49ec7ad8a167.png)

**Comment by elavarasann** [comment]
You have to configure it from Magento admin with your payment details, Stores -> Configuration -> Sales -> Worldpay. Fill all the columns like below,

![wp-configuration](https://user-images.githubusercontent.com/5245575/59265514-1bf1e780-8c63-11e9-9114-0be8c9d3e9db.png)

**Comment by imran-solangin** [comment]
I have configure like this file attached below.

![worldpay-Setting](https://user-images.githubusercontent.com/31388611/59265828-a0426b80-8c5f-11e9-8237-ff995fd9dd11.jpg)

**Comment by elavarasann** [comment]
Please clear the Magento cache and browser cache, then try again.

**Comment by imran-solangin** [comment]
I have cleared cache and browser cache, but it is not working
