### ISSUE TITLE
Issue : Guest Checkout Popup is not displaying

### ISSUE THREAD

**Issue by dhiraj-danode** [Worldpay/Worldpay-Magento2-CG#23]
Steps to Replicate
1. Go to Admin Sales -> Checkout -> Checkout Option and set Allow Guest Checkout to No
2. Add product to cart 
3. Wait for minicart to be updated
4. Click on the minicart
5. Click "Proceed to checkout"

Expected Result:
Magento popup should be shown with options either to log in or register a a new customer

Actual Result:
Customer is being redirected to cart page
Error message "Guest checkout is disabled" is showing

Observation
sapient/module-worldpay/view/frontend/templates/onepage/link.phtml
"Process to Checkout" button behaviour has been changed in above file

data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
Changed to
onclick="location.href='<?php echo $block->getCheckoutUrl() ?>'"

Is this updated for any purpose.

Atatched the error file and expected 
![error](https://user-images.githubusercontent.com/47853083/63273384-8060a100-c2bb-11e9-85af-25165dbf3df9.png)
![expected](https://user-images.githubusercontent.com/47853083/63273386-80f93780-c2bb-11e9-97bc-fc9308912b51.png)

file.

**Comment by elavarasann** [comment]
The issue has been fixed, will be available soon.
