### ISSUE TITLE
Not work in production with minify javascript

### ISSUE THREAD

**Issue by ernesthernandez** [Worldpay/Worldpay-Magento2-CG#25]
The plugin not work in production environment and minified javascript, apparently magento adds extra min.
Production:

https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/hmac-sha256.min.js
https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/components/enc-base64-min.min.js
[ERROR] Failed to load the “Sapient_Worldpay/js/view/payment/method-renderer/cc-method” component.

Correct URL

https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/hmac-sha256.js
https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/components/enc-base64-min.js

![image](https://user-images.githubusercontent.com/11682224/66437827-0c539700-e9e8-11e9-8ea8-83bfe5c6e014.png)

You need to exclude those JS from minification in config.xml

**Comment by elavarasann** [comment]
Hi Ernest Hernandez,
    Thank you for highlighting this, we will add this fix in the upcoming release.
