### ISSUE TITLE
Order Conformation email not sent in Live mode

### ISSUE THREAD

**Issue by jagejobs** [Worldpay/Worldpay-Magento2-CG#28]
![#000000118 _ Orders _ Operations _ Sales _ Magento Admin _ HAILLY LONDON UK](https://user-images.githubusercontent.com/5634108/75653441-9d6f2700-5c83-11ea-9fe1-75a21394cc46.png)
Hi ,
Magento version is 2.3.4, PHP  - 7.1.3, Wordlpay  - 2.1.6.

When in test mode, and order is placed via worldpay, customer gets order confirmation email
But when in Live mode, and order is placed, customer is not getting order Confirmation email
Please advise,

Thanks

Jag

**Comment by chandan-PS** [comment]
Hi @jagejobs 

We have provided the 2.3.4 support in our latest release (q2.20.v2.3.4) and plugin is fully compatible with the 2.3.4 version.

Regards,
Chandan Sinha
