### ISSUE TITLE
pass Encrypted data to order api

### ISSUE THREAD

**Issue by sivajik34** [Worldpay/Worldpay-Magento2-CG#35]
We are using Magento 2 with reactjs as headless frontend.
I think we need to use client side and serverside  encryption.
And our payment action is authorise only.
Where i need to pass encrypted data in order api.
May i know file location for adding encrypted data.
Thanks in advance

**Comment by chandan-PS** [comment]
Hi @sivajik34 , Are you using HPP (re-firect) or Direct inetegration?

**Comment by sivakumarkoduru** [comment]
Our requirement based on below things.
http://support.worldpay.com/support/CNP-API/home.htm#introduction.htm%3FTocPath%3DIntroduction%7C_____0
https://developer.worldpay.com/assets/pdf/us-ecom-pdf/Worldpay_eProtect_Integration_Guide_V4.1.pdf

Is there any magento module is available to support above API's ?
