### ISSUE TITLE
Support for us online payments and payfac

### ISSUE THREAD

**Issue by sivakumarkoduru** [Worldpay/Worldpay-Magento2-CG#36]
Dear Team,
Is it support US online payments and Payfac transactions.
We don't need sub merchants register,we should be able to authorise order amount to sub merchants.

**Comment by chandan-PS** [comment]
Hi @sivakumarkoduru - We will keep you posted on this.

**Comment by Nitubw** [comment]
@sivakumarkoduru Happy to help. Can you please email me at nitu.walker@fisglobal.com, so I can route you to the right person to the right channel? Thank you!

Nitu Walker
Global Enterprise eCommerce
Strategic Partner Manager
Worldpay from FIS 
E:  nitu.walker@fisglobal.com

**Comment by sivakumarkoduru** [comment]
Sent an email.please check

**Comment by sivakumarkoduru** [comment]
@Nitubw  finally u suggested same extension
 https://github.com/Worldpay/Worldpay-Magento2-CG

But i dont see any CNP API implementation in this?
