### ISSUE TITLE
Order Status has not changed

### ISSUE THREAD

**Issue by IThappywork** [Worldpay/Worldpay-Magento2-CG#4]
Order status has not changed after payment is successful  --worldpay

**Comment by RomanLesyk** [comment]
I'm also interested in this feature. It would be great to have an option to update order status if the payment was successful.

**Comment by im-jc** [comment]
Any update? Invoices are not generated even after setting in admin configuration.

**Comment by chandan-PS** [comment]
Hi All,

Please enable Auto Invoice option in the admin.

One can use Sync Status option under order details, if notification is not updating the status.

We have added a feature to add a Cron job as well, if status not updating. please refer the updated document and setup the job.

Regards,
Chandan Sinha
