### ISSUE TITLE
Not compatible with Magento 2.3.5-p2

### ISSUE THREAD

**Issue by prathap2406** [Worldpay/Worldpay-Magento2-CG#44]
{"0":"URI is not valid and cannot be converted into a string","1":"#1 Laminas\\Http\\Header\\AbstractLocation->getUri() called at [vendor\/laminas\/laminas-http\/src\/Header\/AbstractLocation.php:138]\n#2 Laminas\\Http\\Header\\AbstractLocation->toString() called at [vendor\/laminas\/laminas-http\/src\/PhpEnvironment\/Response.php:114]\n#3 Laminas\\Http\\PhpEnvironment\\Response->sendHeaders() called at [generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php:323]\n#4 Magento\\Framework\\App\\Response\\Http\\Interceptor->sendHeaders() called at [vendor\/laminas\/laminas-http\/src\/PhpEnvironment\/Response.php:144]\n#5 Laminas\\Http\\PhpEnvironment\\Response->send() called at [generated\/code\/Magento\/Framework\/App\/Response\/Http\/Interceptor.php:349]\n#6 Magento\\Framework\\App\\Response\\Http\\Interceptor->send() called at [vendor\/magento\/framework\/HTTP\/PhpEnvironment\/Response.php:45]\n#7 Magento\\Framework\\HTTP\\PhpEnvironment\\Response->sendResponse() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#8 Magento\\Framework\\App\\Response\\Http\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#9 Magento\\Framework\\App\\Response\\Http\\Interceptor->Magento\\Framework\\Interception\\\{closure}

**Comment by prathap2406** [comment]
sapient/module-worldpay/Controller/Redirectresult/Redirect.php - $redirecturl = $this->checkoutsession->getWpRedirecturl() - It returns only empty val in magento 2.3.5-p2

**Comment by elavarasann** [comment]
Can you please tell us which version of our Plugin are you using ? and is the customer logged out after redirection ?

**Comment by prathap-fleet** [comment]
Version - 2.1.7
Customer is still logged in only.

**Comment by prathap2406** [comment]
@elavarasann 
Version - 2.1.7
Customer is still logged in only. But couldn't find the root cause of this issue. After upgrading, this happens
