### ISSUE TITLE
Worlpay API service not available on checkout

### ISSUE THREAD

**Issue by Sairam9519** [Worldpay/Worldpay-Magento2-CG#48]
Worlpay API service not available on checkout

**Comment by chandan-PS** [comment]
Hello @Sairam9519 - Can you please share more details about the error and are you experiencing this in Production Env/Test Env or both?

**Comment by Sairam9519** [comment]
04/06/2021 09:54:46data"HTTP\/1.1 401 Unauthorized\r\nDate: Tue, 06 Apr 2021 09:54:46 GMT\r\nServer: Apache\r\nWWW-Authenticate: Basic realm=\"Bibit Merchant XML Login\"\r\nContent-Type: text\/html\r\nContent-Length: 658\r\nP3P: CP=\"NON\"\r\nSet-Cookie: machine=0a854015;path=\/\r\nX-XSS-Protection: 1; mode=block\r\nX-Content-Type-Options: nosniff\r\nStrict-Transport-Security: max-age=3156000; includeSubDomains; preload\r\nX-Cnection: close\r\n\r\n<?xml version=\"1.0\"?>\n<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.1\/\/EN\"\n    \"http:\/\/www.w3.org\/TR\/xhtml11\/DTD\/xhtml11.dtd\">\n<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\" xml:lang=\"en\">\n<head>\n\t<title>401: Requires Authentication<\/title>\n\t<style type=\"text\/css\" media=\"print\"> @import url(\/pictures\/print.css);<\/style>\n\t<style type=\"text\/css\" media=\"screen\"> @import url(\/pictures\/adminstyle-branded.css);<\/style>\n<\/head>\n\n<body class=\"standalone\">\n\t<div class=\"content\"><span class=\"legend\">Requires Authentication<\/span><div class=\"status\">Status: 401<\/div>\n\t\t<p>\n            This request requires HTTP authentication.\n\t\t\t<br \/>\n\t\t<\/p>\n\t<\/div>\n<\/body>\n<\/html>\n"

**Comment by chandan-PS** [comment]
Hello @Sairam9519 - We have checked it at our end and services are up and running well. 
By seeing your logs, this is Unauthorize access exception. Can you please verify all your credentials in MAI and try again?

**Comment by Sairam9519** [comment]
Hello @chandan-PS I checked and do we have an proper document to do integration. Can you please let me know where can I get xml password from MAI account

**Comment by Sairam9519** [comment]
@chandan-PS Upon discussing with worldpay team my issue with MAI got fixed but recieving below on order success do you have any idea on it ?
Exception #0 (Exception): Warning: Cookie paths cannot contain any of the following ',; \t\r\n\013\014' in /var/www/html/earthllite/b2bearthlite/earthlite-b2b/vendor/sapient/module-worldpay/Controller/ThreeDSecure/Auth.php on line 58
