### ISSUE TITLE
Magento 2.3.4-p2 > 2.4.2 Commerce with release-v2.4.2-rc0421 Throws error during setup:upgrade

### ISSUE THREAD

**Issue by AndrewPFBurns** [Worldpay/Worldpay-Magento2-CG#58]
Please see error message and stack trace below during setup:upgrade.

We're upgrading Magento to 2.4.2 from 2.3.4-p2 and using the dev release branch release-v2.4.2-rc0421 of the Worldpay module. 

I've investigate the issue and appears to be around the saving of "klarna_config/klarna_countries_config" config.

`Module 'Sapient_Worldpay':
Upgrading data.. PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Config\Model\Config::getOriginalFieldId() must be an instance of Magento\Config\Model\Config\Structure\Element\Group, instance of Magento\Config\Model\Config\Structure\Element\Field\Interceptor given, called in /magento/vendor/magento/module-config/Model/Config.php on line 279 and defined in /magento/vendor/magento/module-config/Model/Config.php:248
Stack trace:
#0 /magento/vendor/magento/module-config/Model/Config.php(279): Magento\Config\Model\Config->getOriginalFieldId()
#1 /magento/vendor/magento/module-config/Model/Config.php(429): Magento\Config\Model\Config->getField()
#2 /magento/vendor/magento/module-config/Model/Config.php(200): Magento\Config\Model\Config->_processGroup()
#3 /magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Model\Config->save()
#4 /magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Model\Config\Interceptor->___callParent()
#5 /magento/vendor/magento/module-catalog-permi in /magento/vendor/magento/module-config/Model/Config.php on line 248

Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Config\Model\Config::getOriginalFieldId() must be an instance of Magento\Config\Model\Config\Structure\Element\Group, instance of Magento\Config\Model\Config\Structure\Element\Field\Interceptor given, called in /magento/vendor/magento/module-config/Model/Config.php on line 279 and defined in /magento/vendor/magento/module-config/Model/Config.php on line 248

TypeError: Argument 1 passed to Magento\Config\Model\Config::getOriginalFieldId() must be an instance of Magento\Config\Model\Config\Structure\Element\Group, instance of Magento\Config\Model\Config\Structure\Element\Field\Interceptor given, called in /magento/vendor/magento/module-config/Model/Config.php on line 279 in /magento/vendor/magento/module-config/Model/Config.php on line 248

Call Stack:
    0.0003     350344   1. {main}() /magento/bin/magento:0
    0.4371    7037720   2. Magento\Framework\Console\Cli->run(???, ???) /magento/bin/magento:23
    0.4464    7120704   3. Magento\Framework\Console\Cli->doRun(class Symfony\Component\Console\Input\ArgvInput, class Symfony\Component\Console\Output\ConsoleOutput) /magento/vendor/symfony/console/Application.php:149
    0.4464    7120704   4. Magento\Framework\Console\Cli->doRun(class Symfony\Component\Console\Input\ArgvInput, class Symfony\Component\Console\Output\ConsoleOutput) /magento/vendor/magento/framework/Console/Cli.php:115
   10.9444  123766568   5. Magento\Framework\Console\Cli->doRunCommand(class Magento\Setup\Console\Command\UpgradeCommand, class Symfony\Component\Console\Input\ArgvInput, class Symfony\Component\Console\Output\ConsoleOutput) /magento/vendor/symfony/console/Application.php:273
   10.9444  123766568   6. Magento\Setup\Console\Command\UpgradeCommand->run(class Symfony\Component\Console\Input\ArgvInput, class Symfony\Component\Console\Output\ConsoleOutput) /magento/vendor/symfony/console/Application.php:1009
   10.9447  123768720   7. Magento\Setup\Console\Command\UpgradeCommand->execute(class Symfony\Component\Console\Input\ArgvInput, class Symfony\Component\Console\Output\ConsoleOutput) /magento/vendor/symfony/console/Command/Command.php:255
   68.3338  277831968   8. Magento\Setup\Model\Installer->installDataFixtures(array(13), true) /magento/setup/src/Magento/Setup/Console/Command/UpgradeCommand.php:147
   68.3371  277832648   9. Magento\Setup\Model\Installer->handleDBSchemaData(class Magento\Setup\Module\DataSetup, string(4), array(13)) /magento/setup/src/Magento/Setup/Model/Installer.php:960
   68.5428  278868720  10. Sapient\Worldpay\Setup\UpgradeData->upgrade(class Magento\Setup\Module\DataSetup, class Magento\Setup\Model\ModuleContext) /magento/setup/src/Magento/Setup/Model/Installer.php:1059
   68.5556  279131512  11. Magento\Config\Model\Config\Interceptor->save() /magento/vendor/sapient/module-worldpay/Setup/UpgradeData.php:1496
   68.5559  279132848  12. Magento\Config\Model\Config\Interceptor->___callPlugins(string(4), array(0), array(1)) /magento/generated/code/Magento/Config/Model/Config/Interceptor.php:23
   68.5559  279133832  13. Magento\Config\Model\Config\Interceptor->Magento\Framework\Interception\{closure:/magento/vendor/magento/framework/Interception/Interceptor.php:104-151}(...variadic()) /magento/vendor/magento/framework/Interception/Interceptor.php:153
   68.5562  279136664  14. Magento\CatalogPermissions\Model\Indexer\Plugin\ConfigData->aroundSave(class Magento\Config\Model\Config\Interceptor, class Closure) /magento/vendor/magento/framework/Interception/Interceptor.php:135
   68.5583  279140968  15. Magento\Config\Model\Config\Interceptor->Magento\Framework\Interception\{closure:/magento/vendor/magento/framework/Interception/Interceptor.php:104-151}(...variadic()) /magento/vendor/magento/module-catalog-permissions/Model/Indexer/Plugin/ConfigData.php:97
   68.5583  279141000  16. Magento\Config\Model\Config\Interceptor->___callParent(string(4), array(0)) /magento/vendor/magento/framework/Interception/Interceptor.php:138
   68.5583  279141000  17. Magento\Config\Model\Config\Interceptor->save() /magento/vendor/magento/framework/Interception/Interceptor.php:58
   68.5603  279142760  18. Magento\Config\Model\Config\Interceptor->_processGroup(string(37), array(1), array(5), string(8), array(0), array(0), class Magento\Framework\DB\Transaction, class Magento\Framework\DB\Transaction) /magento/vendor/magento/module-config/Model/Config.php:200
   68.5607  279144504  19. Magento\Config\Model\Config\Interceptor->getField(string(8), string(37), string(15)) /magento/vendor/magento/module-config/Model/Config.php:429
   68.5607  279144584  20. Magento\Config\Model\Config\Interceptor->getOriginalFieldId(class Magento\Config\Model\Config\Structure\Element\Field\Interceptor, string(15)) /magento/vendor/magento/module-config/Model/Config.php:279`

**Comment by EvanRijn** [comment]
We having the same issue.
