### ISSUE TITLE
Argument 1 passed to Magento\\Framework\\Exception\\LocalizedException::__construct() must be an instance of Magento\\Framework\\Phrase, string given,

### ISSUE THREAD

**Issue by SegaBoy64** [Worldpay/Worldpay-Magento2-CG#64]
We're getting the above error on the following:

Sapient\Worldpay\Cron\OrderSyncStatus::_applyPaymentUpdate()

`throw new \Magento\Framework\Exception\LocalizedException($e->getMessage());`

Magento expects a type of Magento\Framework\Phrase to be passed instead of the string above.

**Comment by dfelton** [comment]
Looks like this was fixed in https://github.com/Worldpay/Worldpay-Magento2-CG/commit/82a743534819bd9ab17d568c1261d4770c9b3dae#diff-aadcbe9a801e915b115fafc22f2faf6f77874caa8d0c6cc3bd030ea3d35c72ba
