### ISSUE TITLE
Sapient\WorldPay\Model\Token\AccessDeniedException does not exist

### ISSUE THREAD

**Issue by jajajaime** [Worldpay/Worldpay-Magento2-CG#71]
Getting an error when trying to update a credit card from the customer account and the customer is not the owner of it.
The error references that the exception class does not exist, and sure enough, it is not there.

```Error: Class 'AccessDeniedException' not found in /var/www/app/code/Sapient/Worldpay/Model/Token/WorldpayToken.php:74```

https://github.com/Worldpay/Worldpay-Magento2-CG/blob/master/Model/Token/WorldpayToken.php#L74

**Comment by chandan-PS** [comment]
@jajajaime - Which Magento version and Worldpay plugin version are you using?

**Comment by jajajaime** [comment]
Magento 2.4.3-p1
Sapient\WorldPay 2.4.2-p0821

**Comment by chandan-PS** [comment]
@jajajaime Please note our plugin 2.4.2-p0821 is not compatible with Magento 2.4.3.

We have recently released our new version 2.4.3-rc1221 for magento 2,4,3 version.

Also, our latest release 2.4.3-rc1221 is not tested with magento 2,4,3-p1 and we will have a future release for 2.4.3-p1 as well.

**Comment by jajajaime** [comment]
@chandan-PS sure. There's still the fact that that class does not exist that the code is trying to reference.

**Comment by chandan-PS** [comment]
@jajajaime - We will check this from our end and update you back.
