### ISSUE TITLE
Collection namespace is incorrect

### ISSUE THREAD

**Issue by jajajaime** [Worldpay/Worldpay-Magento2-CG#73]
The namespace in 
https://github.com/Worldpay/Worldpay-Magento2-CG/blob/master/Model/ResourceModel/Worldpayment/Collection.php

is 
```namespace Sapient\Worldpay\Model\ResourceModel\Collection;```

but it should be
```namespace Sapient\Worldpay\Model\ResourceModel\Worldpayment;```

This makes Composer 1 complain about it, and states that Composer 2 will not autoload this file.

![image](https://user-images.githubusercontent.com/13631233/153075894-fe46c00e-8fd2-43f6-b10b-cad4fe1956e5.png)

This was brought up by @sajidpatel 3 years ago in #16, but the issue was closed without a resolution.

**Comment by chandan-PS** [comment]
Thanks @jajajaime, we will consider this change in our next release.
