### ISSUE TITLE
Unable to unserialize value. Error: Syntax error Sapient\\Worldpay\\Helper\\Recurring->getAdminLabels()

### ISSUE THREAD

**Issue by cs-media** [Worldpay/Worldpay-Magento2-CG#77]
Every time we try to edit a product in the backend, we are getting an exception.

**How to reproduce:**

- Login as Admin user.
- Go to edit any product in Catalog->Products

**Environment:**
Magento 2.4.3-p1
Saptient Worldpay 2.4.3-rc1221

**Full Report:**
{"0":"Unable to unserialize value. Error: Syntax error","1":"#1 Sapient\\Worldpay\\Helper\\Recurring->getAdminLabels() called at [vendor\/sapient\/module-worldpay\/Ui\/DataProvider\/Product\/Form\/Modifier\/RecurringPlans.php:106]\n#2 Sapient\\Worldpay\\Ui\\DataProvider\\Product\\Form\\Modifier\\RecurringPlans->modifyMeta() called at [vendor\/magento\/module-catalog\/Ui\/DataProvider\/Product\/Form\/ProductDataProvider.php:73]\n#3 Magento\\Catalog\\Ui\\DataProvider\\Product\\Form\\ProductDataProvider->getMeta() called at [vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php:330]\n#4 Magento\\Framework\\View\\Element\\UiComponentFactory->mergeMetadata() called at [vendor\/magento\/framework\/View\/Element\/UiComponentFactory.php:231]\n#5 Magento\\Framework\\View\\Element\\UiComponentFactory->create() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:140]\n#6 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->generateComponent() called at [vendor\/magento\/framework\/View\/Layout\/Generator\/UiComponent.php:103]\n#7 Magento\\Framework\\View\\Layout\\Generator\\UiComponent->process() called at [vendor\/magento\/framework\/View\/Layout\/GeneratorPool.php:93]\n#8 Magento\\Framework\\View\\Layout\\GeneratorPool->process() called at [vendor\/magento\/framework\/View\/Layout.php:365]\n#9 Magento\\Framework\\View\\Layout->generateElements() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:68]\n#10 Magento\\Framework\\View\\Layout\\Interceptor->generateElements() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:129]\n#11 Magento\\Framework\\View\\Layout\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Page\/Builder.php:65]\n#12 Magento\\Framework\\View\\Page\\Builder->generateLayoutBlocks() called at [vendor\/magento\/framework\/View\/Layout\/Builder.php:65]\n#13 Magento\\Framework\\View\\Layout\\Builder->build() called at [vendor\/magento\/framework\/View\/Layout.php:271]\n#14 Magento\\Framework\\View\\Layout->build() called at [vendor\/magento\/framework\/View\/Layout.php:896]\n#15 Magento\\Framework\\View\\Layout->getBlock() called at [generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php:293]\n#16 Magento\\Framework\\View\\Layout\\Interceptor->getBlock() called at [vendor\/magento\/module-backend\/Model\/View\/Result\/Page.php:26]\n#17 Magento\\Backend\\Model\\View\\Result\\Page->setActiveMenu() called at [vendor\/magento\/module-catalog\/Controller\/Adminhtml\/Product\/Edit.php:82]\n#18 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit->execute() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#19 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#20 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#21 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/Edit\/Interceptor.php:23]\n#22 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->execute() called at [vendor\/magento\/framework\/App\/Action\/Action.php:111]\n#23 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor\/magento\/module-backend\/App\/AbstractAction.php:151]\n#24 Magento\\Backend\\App\\AbstractAction->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#25 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#26 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/module-backend\/App\/Action\/Plugin\/Authentication.php:143]\n#27 Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:135]\n#28 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#29 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/Edit\/Interceptor.php:32]\n#30 Magento\\Catalog\\Controller\\Adminhtml\\Product\\Edit\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/FrontController.php:245]\n#31 Magento\\Framework\\App\\FrontController->getActionResponse() called at [vendor\/magento\/framework\/App\/FrontController.php:212]\n#32 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor\/magento\/framework\/App\/FrontController.php:147]\n#33 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:58]\n#34 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:138]\n#35 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor\/magento\/framework\/Interception\/Interceptor.php:153]\n#36 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php:23]\n#37 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor\/magento\/framework\/App\/Http.php:116]\n#38 Magento\\Framework\\App\\Http->launch() called at [generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php:23]\n#39 Magento\\Framework\\App\\Http\\Interceptor->launch() called at [vendor\/magento\/framework\/App\/Bootstrap.php:264]\n#40 Magento\\Framework\\App\\Bootstrap->run() called at [pub\/index.php:29]\n","url":"\/phil_admin\/catalog\/product\/edit\/id\/690\/key\/17660bbaba8b6c6efbd7f10f6ee9ce8dfa424b4e821218bfdbe176fab72771a2\/","script_name":"\/pub\/index.php","report_id":"8cc3e2ed879043ec6a8d6b8a353391d500a5d98b147ece554730362b723f0b89"}

It looks to be something to do with Recurring Payments / Subscriptions, but we aren't using any of that. 

Any help resolving this would be greatly received. Thanks :)

**Comment by elavarasann** [comment]
Thanks for reaching us, we will check it and update you.
