### ISSUE TITLE
Magento 2.4.4 with PHP8.1. Sapient_Worldpay  is not working

### ISSUE THREAD

**Issue by sanjusmaliyelil** [Worldpay/Worldpay-Magento2-CG#86]
Hi,

We are getting the below errors with the Sapient_Worldpay extension when we upgraded Magento to 2.4.4. Please assist us to fix it. 
1. 1/9 [===>------------------------] 11% 5 secs 170.0 Misyntax error, unexpected fully qualified name "\Payment\State"#0 D:\wamp3.2.6\www\alexandra-code\vendor\composer\ClassLoader.php(428): Composer\Autoload\includeFile('D:\\wamp3.2.6\\ww
...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Sapient\\Worldpa...')
 
2.Fatal error: Declaration of Sapient\Worldpay\Logger\WorldpayLogger::addRecord($level, $message, array $context = []) must be compatible with
Monolog\Logger::addRecord(int $level, string $message, array $context = []): bool in D:\wamp3.2.6\www\alexandra-code\vendor\sapien
t\module-worldpay\Logger\WorldpayLogger.php on line 9
 
 
3. Laminas\Code\Reflection\ClassReflection Object
(
[name] => Sapient\Worldpay\Api\PaymentTypeInterface
[docBlock:protected] =>
)
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data,
Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName(): Argument #2 ($typeName) must be of type string, null given, called in D:\wamp3.2.6\www\alexandra-code\vend
or\magento\framework\Reflection\TypeProcessor.php on line 550

In AbstractFactory.php line 131:

Type Error occurred when creating object: Magento\Framework\Communication\Config\Data,
Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName(): Argument #2 ($typeName) must be of type string, null given, called in D:\wamp3.2.6\www\alexandra-code
\vendor\magento\framework\Reflection\TypeProcessor.php on line 550

Many thanks!
Sanju

**Comment by obsergiu** [comment]
we've hit the same issue 

i do understand that the current module is not yet fully compatible with M2.4.4 but still ...

**Comment by deemantha22** [comment]
Hi,

Unfortunately, we are getting same issue. I am on php 7.4 and Magento 2.4.4.

Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in vendor/magento/framework/Reflection/TypeProcessor.php on line 550

**Comment by chandan-PS** [comment]
@sanjusmaliyelil , @obsergiu and @deemantha22 - We have not released the 2.4.4 compatible plugin yet. Please check back this space after mid of June for our latest release updates.

**Comment by zamoroka** [comment]
The fix is here: https://github.com/Worldpay/Worldpay-Magento2-CG/pull/87

**Comment by deemantha22** [comment]
Hi @zamoroka 

Thanks for the update but I am still getting same error after applying patch you posted(vendor/sapient/module-worldpay/Model/Payment/Update/Authorised.php)

```
Module 'Magento_AdvancedPricingImportExport':
Module 'Magento_Directory':
Module 'Magento_Amqp':
Type Error occurred when creating object: Magento\Framework\Communication\Config\Data, Argument 2 passed to Magento\Framework\Reflection\TypeProcessor::resolveFullyQualifiedClassName() must be of the type string, null given, called in /vendor/magento/framework/Reflection/TypeProcessor.php on line 550
```

**Comment by zamoroka-vaimo** [comment]
@deemantha22 , oh, I missed the 3rd point :) 
It was not reproduced on my project, so the fix in https://github.com/Worldpay/Worldpay-Magento2-CG/pull/87/commits is for point 1 and 2 only

**Comment by zamoroka** [comment]
@deemantha22 , oh, I missed the 3rd point :)
It was not reproduced on my project, so the fix in https://github.com/Worldpay/Worldpay-Magento2-CG/pull/87/commits is for point 1 and 2 only

**Comment by deemantha22** [comment]
@zamoroka excellent, it worked. Seems like it was the dot. I had to remove dot from all below not only PaymentTypeInterface.

HostedUrlInterface
HistoryInterface
LatAmInstalInterface

**Comment by sanjusmaliyelil** [comment]
Yea I saw this. Is it possible to download it as .patch file?
We are using the composer version of the extension. So should be
applied via patch.

Many Thanks,
Sanju S Maliyelil , Senior Software Engineer
Mobile: +91 9496089220
CORRA.COM /LINKEDIN <https://www.linkedin.com/company-beta/141347/>/TWITTER
<https://twitter.com/GoCorra>

**Comment by zamoroka** [comment]
@sanjusmaliyelil 
https://letmegooglethat.com/?q=github+create+patch+from+pull+request

**Comment by sanjusmaliyelil** [comment]
Hi @zamoroka ,

I have downloaded the patch and applied it. di:compile is successful. But while running setup:upgrade got below error
` The XML in file "D:/wamp3.2.6/www/alexandra-code/vendor/sapient/module-worldpay/etc/db_schema.xml" is invalid:
Element 'column', attribute 'padding': The attribute 'padding' is not allowed.
Line: 5

Element 'column', attribute 'unsigned': The attribute 'unsigned' is not allowed.
Line: 5

Element 'column', attribute 'identity': The attribute 'identity' is not allowed.
Line: 5

Element 'column', attribute 'padding': The attribute 'padding' is not allowed.
Line: 100

Element 'column', attribute 'unsigned': The attribute 'unsigned' is not allowed.
Line: 100

Element 'column', attribute 'identity': The attribute 'identity' is not allowed.
Line: 100

Verify the XML and try again.
   `

**Comment by sanjusmaliyelil** [comment]
Hi @zamoroka ,

I got  patch for the pull request https://github.com/Worldpay/Worldpay-Magento2-CG/pull/83/files and I have successfully completed the setup upgrade.

Thanks!
Sanju

**Comment by sanjusmaliyelil** [comment]
Hi @zamoroka ,

While trying to place order using world pay , getting below error as a response.
{"message":"Deprecated Functionality: Constant FILTER_SANITIZE_STRING is deprecated in \/app\/c7t5qvabrjwco_stg\/vendor\/sapient\/module-worldpay\/Model\/Mapping\/Service.php on line 315"}

Can you please let us know how we can resolve this?

Thanks!
Sanju

**Comment by sanjusmaliyelil** [comment]
Hi @zamoroka ,

Any update regarding above issue?

Thanks!
Sanju
