### ISSUE TITLE
Magento 2.4.4 | User ID and Type ID cannot be empty

### ISSUE THREAD

**Issue by cyildirim** [Worldpay/Worldpay-Magento2-CG#89]
**Description**
As Magento now uses `Magento\JwtUserToken\Model\Issuer` to generate token it goes through following check 

```
    if (!$userContext->getUserId() || !$userContext->getUserType()) {
            throw new UserTokenException('User ID and Type ID cannot be empty');
        }
```

This causes error as for guest users customer id is not assigned. 

**Error message :** 
```
1 exception(s):
Exception #0 (Magento\Integration\Api\Exception\UserTokenException): User ID and Type ID cannot be empty

Exception #0 (Magento\Integration\Api\Exception\UserTokenException): User ID and Type ID cannot be empty
<pre>#1 Magento\JwtUserToken\Model\Issuer\Interceptor->create() called at [vendor/magento/module-integration/Model/Oauth/Token.php:246]
#2 Magento\Integration\Model\Oauth\Token->createCustomerToken() called at [vendor/sapient/module-worldpay/Block/Webpayment.php:173]
#3 Sapient\Worldpay\Block\Webpayment->getCustomerToken() called at [generated/code/BAT/Worldpay/Block/Webpayment/Interceptor.php:113]

-> view/frontend/templates/webpayment.phtml:9

```

----

**Suggested Solution**

`createCustomerToken` is deprecated. Magento suggests to use Issuer (`Magento\Integration\Api\UserTokenIssuerInterface`) which is used by `Magento_JwtUserToken` module recently introduced. See below [createCustomerToken](https://github.com/magento/magento2/blob/2.4.4/app/code/Magento/Integration/Model/Oauth/Token.php#L241)
https://github.com/magento/magento2/blob/2.4.4/app/code/Magento/JwtUserToken/Model/Issuer.php#L63

**Comment by samcleathero** [comment]
I've also had this issue occurring with logged in users on CMS pages. I haven't dug too deep into what the underlying issue is, but changing line 209 of `Block/Webpayment.php` from

`$customerId = $this->_customerSession->getCustomer()->getId();`

to

`$customerId = $this->_customerSession->getCustomerId();`

seems to have fixed the issue for me.

**Comment by elavarasann** [comment]
Hi,
We have checked this issue in our end but we are not able to reproduce this issue. Anyway thanks for the intimation.
