### ISSUE TITLE
How to install module

### ISSUE THREAD

**Issue by adamlavery** [Worldpay/Worldpay-Magento2-CG#9]
The installation instructions for the module are somewhat brief, containing just the statement:

_Worldpay Extension is hosted at https://github.com/Worldpay/Worldpay-Magento-CG , To run below
installation steps, access to repository is required._

Nothing further on what this actually means. Complete instructions should be included for those not familiar with this process. Anyhow, added the following to Magento composer.json repositories section:

`		"sapient": {
			"type": "composer",
			"url": "https://github.com/Worldpay/Worldpay-Magento-CG"
		}
`

Now running **composer require sapient/module-worldpay** getting the following:

[Composer\Downloader\TransportException]
  The "https://github.com/Worldpay/Worldpay-Magento-CG/packages.json" file could not be downloaded (HTTP/1.1 301 Moved Permanently)

Should it not be using the module's composer.json? Is the repository definition correct? Any ideas?

**Comment by KrizzyB** [comment]
I added:
`{"type": "vcs", "url": "git@github.com:Worldpay/Worldpay-Magento-CG.git"}` 
to the repositories section of Magento's composer.json then ran:
**composer require sapient/module-worldpay**
and it worked for me...

**Comment by elavarasann** [comment]
We have found that there are some gaps in our documentation / user guide. We will release new feature with updated documentation soon. Thanks for the highlights.
