### ISSUE TITLE
JWT is created on the frontend which is significant security issue

### ISSUE THREAD

**Issue by mekedron** [Worldpay/Worldpay-Magento2-CG#91]
This is what's said by your documentation:
![Screenshot from 2022-06-23 20-31-18](https://user-images.githubusercontent.com/2446589/175349359-778b90b3-5b07-4c83-84c1-5253995f37c1.png)

This is what you do:
https://github.com/Worldpay/Worldpay-Magento2-CG/blob/92407334c9e8e7febcd6037ab2ae008120bdf6e7/view/frontend/templates/jwtiframe.phtml#L46

I think you MUST create JWT on the backend instead of frontend

**Comment by elavarasann** [comment]
We have fixed this issue in our side already in previous releases.
