### ISSUE TITLE
3DSecure authorize payment log out/session issue

### ISSUE THREAD

**Issue by ydmytrunetsspace** [Worldpay/Worldpay-Magento2-CG#96]
Magento ver. 2.4.1 B2B
Browser: Chrome Version 103.0.5060.114
sapient/module-worldpay: 2.4.1-rc1220

**Steps to reproduce:**
1. Go to checkout, fill form, press Place order. Magento redirects me to 3DSecure authorize payment page. I press cancel Payment. I am redirected to Magento card page. (Alternative is: I fill incorrect credit card information)

2. Second time, I do the same, but on Authorize Payment page I just waits until payment will cancel by timeout. 

**Actual result:**
I am redirected to Magento card page, but I am logger out. I as a customer losing my Basket, when I log in. 

**Expected result:** 
I am redirected to Magento card page and I am logged in customer. 

**Additional info:**
This bug is rarely reproduced. Approximately from 10 attempt it will occurs once.

**Comment by elavarasann** [comment]
We are not able to reproduce the issue. Please update your plugin to our latest version.
https://github.com/Worldpay/Worldpay-Magento2-CG/releases/tag/2.4.5-p10123
