### ISSUE TITLE
Getting error while running setup upgrade with version 2.4.3-p20622

### ISSUE THREAD

**Issue by sanjusmaliyelil** [Worldpay/Worldpay-Magento2-CG#97]
Hi,
We are getting this error while running the setup upgrade on the latest version of the Worldpay module code

Unable to apply data patch Sapient\Worldpay\Setup\Patch\Data\DefaultConfigurations for module Sapient_Worldpay. Original exception message: Warning: foreach() argument must be of type array|object, string given in /xxxx/vendor/sapient/module-worldpay/Model/System/Config/Backend/MyAccountException.php on line 81

Thanks!
Sanju

**Comment by elavarasann** [comment]
This issue has been resolved in our latest version. So, please upgrade your plugin.
https://github.com/Worldpay/Worldpay-Magento2-CG/releases/tag/2.4.5-p10123
